joint_dim: 128

image:
  cls: i2t.model_rubert.ModalityEncoder
  args:
    output_dim: ${model.joint_dim}
    normalize: True
    encoder:
      cls: i2t.model_rubert.ImageModel
      args:
        encoder_name: resnet50
        weights: imagenet

text:
  cls: i2t.model_rubert.ModalityEncoder
  args:
    output_dim: ${model.joint_dim}
    normalize: True
    encoder:
      cls: i2t.model_rubert.TextModel
      args: 
        model_path: /home/devel/mlcup_cv/baseline/text_models/rubert-tiny

