optimizer:
  cls: torch.optim.Adam
  args:
    lr: 1.0e-3
    weight_decay: 1.0e-6

lr_scheduler:
  scheduler:
    cls: torch.optim.lr_scheduler.MultiStepLR
    args:
      milestones: [1, 2]
      gamma: 0.1
  interval: epoch
